version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: strapi-postgres
    restart: always
    environment:
      POSTGRES_USER: ted
      POSTGRES_PASSWORD: tedpassword
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - strapi-net

volumes:
  pgdata:

networks:
  strapi-net:
    driver: bridge
